apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: tiketibet
build:
  local:
    push: false
  artifacts:
    - image: sanderha/tiketibet-auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
